### ISSUE TITLE
Support for Babel 6

### ISSUE THREAD

**Issue by martindederer** [jurassix/react-display-name#1]
The .babelrc file in this project uses babel 5 syntax. This prevents the usage of babel 6 in a project which has react-display-name in its dependency tree as far is i understand.

Are you interested in a PR which includes all the necessary changes for a switch to babel 6?

**Comment by jurassix** [comment]
@martindederer Yes please submit PR. Thanks.

**Comment by jurassix** [comment]
react-display-name@0.2.3
