### ISSUE TITLE
Test files should not be published

### ISSUE THREAD

**Issue by jaydenseric** [jurassix/react-display-name#13]
The `lib/spec/` directory is being published unnecessarily, causing the install size to be 10.3Kb instead of the few bytes expected: https://packagephobia.now.sh/result?p=react-display-name.

<img width="275" alt="screen shot 2018-09-10 at 1 00 49 pm" src="https://user-images.githubusercontent.com/1754873/45274197-97b6dc00-b4f9-11e8-9bcb-2117b7b49cfe.png">

The fix should be pretty easy; something like adding `!lib/spec` to the end of the package.json `files` field array.

You can run `npm pack` in the repo to see if it's working: https://docs.npmjs.com/cli/pack.

**Comment by jurassix** [comment]
Agreed. I’ll exclude the tests. Thx for reporting the issue.

**Comment by jurassix** [comment]
Upgraded all the libs, having an issue with the tests now. I'll work through it soon and resolve this request.

**Comment by jurassix** [comment]
This should be fixed in latest release `v0.2.5`

**Comment by jurassix** [comment]
please reopen if still an issue.
