### ISSUE TITLE
Package dependencies are too broad

### ISSUE THREAD

**Issue by FlyingDR** [jurassix/react-display-name#5]
Currently this very simple package have too much dependencies and at least some of them are outdated. 

For example it depends on [deprecated](https://www.npmjs.com/package/babel-preset-es2015-loose) package [babel-preset-es2015-loose](https://github.com/jurassix/react-display-name/blob/master/package.json#L36). It also depends on [stage-0](https://github.com/jurassix/react-display-name/blob/master/package.json#L38) preset while it seems to be enough to have just [babel-plugin-transform-class-properties](https://www.npmjs.com/package/babel-plugin-transform-class-properties) that is currently at stage 2.

**Comment by jurassix** [comment]
Thanks for the issue. I agree there are a lot of deps for about 5 lines of code, but at lease these are all DevDependencies. I'll update the deps and publish a new release.

**Comment by jurassix** [comment]
fixed in react-display-name@0.2.1
