### ISSUE TITLE
Error: Couldn't find preset "es2015-loose"

### ISSUE THREAD

**Issue by prescottprue** [jurassix/react-display-name#6]
Getting this error when attempting to use with `react-native`:

`error: bundling: Error: Couldn't find preset "es2015-loose" relative to directory`

I believe it is releated to the fact that `.babelrc` file is included in npm publishing. If you add `.babelrc` to `.npmignore`, it should fix it.

Will try to create a PR soon.

**Comment by jurassix** [comment]
Yup, the `.babelrc` file should be ignored on npm. PR welcome.

**Comment by jurassix** [comment]
react-display-name@0.2.3
